# Generated by Django 4.0.3 on 2022-12-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_potentialcustomer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='name',
            new_name='sales_person',
        ),
    ]
