# Generated by Django 4.0.3 on 2022-12-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_salerecord_sale_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleRecord',
            new_name='SalesRecord',
        ),
    ]
