# Generated by Django 4.0.3 on 2022-12-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_rename_salerecord_salesrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='sales_person',
            new_name='name',
        ),
    ]
