# Generated by Django 4.0.3 on 2022-12-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_appointment_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
